package com.model.entity.npc;

import java.math.BigInteger;

import com.view.GUI;

/**
 * TODO: Write this doc after class is formed.
 *
 * @author Christopher
 *
 */
public class Enemy extends com.model.entity.GameCharacter {

	/* Experience gained for defeating this Character. */
	private BigInteger xpValue;

	/**
	 * Generates an enemy based on a specific profile. This should be
	 * pre-generated by the game engine.
	 *
	 * @param profile the profile describing the enemy.
	 */
	public Enemy(EnemyProfile profile) {
		super(profile.name, profile.maxHP, profile.maxMana,
				profile.attackDamage);
		this.xpValue = profile.xpValue;
	}

	/**
	 * Generates an enemy based on a specific profile. This should be
	 * pre-generated by the game engine.
	 *
	 * @param profile the profile describing the enemy.
	 * @param view the GUI to send messages to.
	 */
	public Enemy(EnemyProfile profile, GUI view) {
		super(profile.name, view, profile.maxHP, profile.maxMana,
				profile.attackDamage);
		this.xpValue = profile.xpValue;
	}

	/**
	 * @return the xp value of this enemy.
	 */
	public BigInteger getXPValue() {
		return xpValue;
	}

}
